---
# tasks file for elastic-installer

# Install the elastic repos and base OS updates
- name: "{{ ansible_os_family }} Install"
  tags: [ 'ps::install' ]
  include: "{{ ansible_os_family }}.yml"
  when: ansible_os_family | default('') != ''

- name: Disable SELinux
  selinux:
    state: disabled
  register: sel

- name: reboot
  reboot:
  when: sel.changed

- name: remove erlang
  yum:
    name: erlang*
    state: absent

- name: download erlang
  yum:
    name:  https://github.com/rabbitmq/erlang-rpm/releases/download/v22.3.4.2/erlang-22.3.4.2-1.el7.x86_64.rpm 
    state: present

# - name: mount dir
#   shell:  mount -o remount,exec /tmp

- name: import elasticsearch key
  rpm_key:
   key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
   state: present

#XXX copy
- name: copying elastic repo
  get_url:
    url: https://raw.githubusercontent.com/perfsonar/archiving-sandbox/master/toolkit/files/elastic.repo
    dest: /etc/yum.repos.d/elastic.repo

- name: copying rabbitmq repo
  get_url:
    url: https://raw.githubusercontent.com/perfsonar/archiving-sandbox/master/central-archive/files/rabbit.repo
    dest: /etc/yum.repos.d/rabbit.repo

- name: yum clean all
  command: yum clean all
  args:
    warn: no

- name: install gcc
  yum:
    state: present
    name:
      - gcc

- name: install kernel-devel
  yum:
    state: present
    name:
      - kernel-devel

- name: install kernel-headers
  yum:
    state: present
    name:
      - kernel-headers

- name: install dkms
  yum:
    state: present
    name:
      - dkms

- name: install make
  yum:
    state: present
    name:
      - make

- name: install bzip2
  yum:
    state: present
    name:
      - bzip2

- name: install python-pika
  yum:
    state: present
    name:
      - python-pika

- name: install python-psutil
  yum:
    state: present
    name:
      - python-psutil

- name: install python3
  yum:
    state: present
    name:
      - python3

- name: install python3-requests
  yum:
    state: present
    name:
      - python3-requests

- name: install elasticsearch
  yum:
    state: present
    name:
      - elasticsearch

- name: install rabbitmq-server
  yum:
    state: latest 
    name:
      - rabbitmq-server

- name: install java-11-openjdk
  yum:
    state: present
    name:
      - java-11-openjdk

#- name: install package
#  yum:
#    state: present
#    name:
#      - gcc
#      - kernel-devel
#      - kernel-headers
#      - dkms
#      - make
#      - bzip2
#      - python-pika
#      - python-psutil
#      - python3
#      - python3-requests
#      - elasticsearch
#      - erlang
#      - rabbitmq-server
#      - java-11-openjdk

- name: newer java for logstash
  get_url:
    url: https://raw.githubusercontent.com/perfsonar/archiving-sandbox/master/toolkit/files/java.sh
    dest: /etc/profile.d/java.sh

- name: execute script
  shell: source /etc/profile.d/java.sh

- name: java 11 setup
  shell: "JAVA_HOME=/usr/lib/jvm/jre-11 yum install -y logstash"


- name: copying 
  shell: "echo \"JAVA+HOME=/usr/share/elasticsearch/jdk\" >> /etc/sysconfig/logstash"

- name: reload daemon
  systemd:
    daemon_reload: yes

- name: start rabbitmq
  systemd:
    enabled: yes
    name: rabbitmq-server
    state: started

- name: enable rabbitmq-management
  rabbitmq_plugin:
    names: rabbitmq_management
    state: enabled

- name: add user
  rabbitmq_user:
    user: elastic
    password: elastic
    vhost: /
    configure_priv: .*
    read_priv: .*
    write_priv: .*
    state: present
    
    
- name: enable elastic
  systemd:
    enabled: yes
    name: elasticsearch.service
    state: started

- name: create dir
  file:
    path: /usr/lib/perfsonar/scripts
    state: directory
    mode: 0755

- name: load script
  get_url:
    url: https://raw.githubusercontent.com/perfsonar/archiving-sandbox/master/toolkit/scripts/pselastic_secure.sh
    dest: /usr/lib/perfsonar/scripts/pselastic_secure.sh
    mode: 0755

- name: copy andys pselastic_setup
  copy:
    src: pselastic_setup
    dest: /usr/lib/
    mode: 0755

- name: run secure script
  script: /usr/lib/perfsonar/scripts/pselastic_secure.sh

- name: copy logstash pipeline config
  copy:
    src: logstash_pipeline/
    dest: /etc/logstash/conf.d/
    force: yes

- name: copy logstash output config
  get_url:
    url: https://raw.githubusercontent.com/perfsonar/archiving-sandbox/master/toolkit/files/99-outputs.conf
    dest: /etc/logstash/conf.d/
    force: yes

- name: copy pssid logstash input-output config
  get_url:
    url: https://raw.githubusercontent.com/UMNET-perfSONAR/pSSID/master/logstash_conf/pssid_conf.d/pssid-input-output.conf
    dest: /etc/logstash/pssid_conf.d/
    force: yes

- name: copy pssid scan and ssid bad coverage filter
  get_url:
    url: https://raw.githubusercontent.com/UMNET-perfSONAR/pSSID/master/logstash_conf/pssid_conf.d/01-pssid-scan-filter.conf
    dest: /etc/logstash/pssid_conf.d/
    force: yes

- name: create a link
  file:
    src: /etc/logstash/conf.d
    dest: /usr/share/logstash/pipeline
    state: link
 
- name: Create second pipeline for pssid
  lineinfile:
    path: /etc/logstash/pipelines.yml
    line: '- pipeline.id: second'
    
- name: Create second pipeline for pssid
  lineinfile:
    path: /etc/logstash/pipelines.yml
    line: '  path.config: "/etc/logstash/pssid_conf.d/*.conf"'

- name: enable logstash
  systemd:
    name: logstash.service
    state: started

- name: get kibana key
  rpm_key:
   key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
   state: present

- name: get kibana
  get_url:
    url: "https://artifacts.elastic.co/downloads/kibana/kibana-7.7.0-x86_64.rpm"
    dest: ~/ansible

- name: install kibana
  yum:
    name: kibana
    state: present

- name: reload daemon
  systemd:
    daemon_reload: yes

- name: start kibana
  systemd:
    enabled: yes
    name: kibana.service
    state: started

- name: setup kibana listening
  lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: "^#server.host: "
    line: "server.host: \"0.0.0.0\""

- name: hostname
  slurp:
    src: /etc/perfsonar/elastic/auth_setup.out
  register: p

- name: Set Password
  set_fact:
    your_password: "{{ p['content'] | b64decode | regex_findall('elastic = (.*)')| first }}"

- name: input password
  lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: '^#elasticsearch.password: '
    line: "elasticsearch.password: {{your_password}}"

- name: more formatting
  lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: '^#elasticsearch.username: '
    line: "elasticsearch.username: \"kibana\""

- name: authencation off
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    regexp: '^xpack.security.enabled: '
    line: "xpack.security.enabled: false"
 
- name: turn on alerting elastic
  lineinfile: 
    path: /etc/elasticsearch/elasticsearch.yml
    line: 'xpack.security.enabled: false'

- name: turn on alerting elastic
  lineinfile:
    path: /etc/elasticsearch/elasticsearch.yml
    line: 'xpack.watcher.enabled: true'

- name: turn on alerting kibana
  lineinfile:
    path: /etc/kibana/kibana.yml
    line: 'xpack.security.enabled: false'
    
- name: turn on alerting kibana
  lineinfile:
    path: /etc/kibana/kibana.yml
    line: 'xpack.watcher.enabled: true'
    
 #can be any key bigger than 31 character
- name: turn on alerting kibana
  lineinfile:
    path: /etc/kibana/kibana.yml
    line: 'xpack.encryptedSavedObjects.encryptionKey: qwertyuiopasdfghjklzxcvbnmqwertyui'
    
- name: reload elasticsearch
  systemd:
    name: elasticsearch.service
    state: restarted

- name: reload kibana
  systemd:
    name: kibana.service
    state: restarted
